// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "TeleOpTankDrive.h"
TeleOpTankDrive::TeleOpTankDrive() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::theDriveTrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::intakeArm);
}
// Called just before this Command runs the first time
void TeleOpTankDrive::Initialize() {
	
}
// Called repeatedly when this Command is scheduled to run
void TeleOpTankDrive::Execute() {
	// control the robot drive motors
	Joystick *left_diver_joystick = Robot::oi->getLeftDriveJoystick();
	Joystick *right_diver_joystick = Robot::oi->getRightDriveJoystick();
	Robot::theDriveTrain->runTankDrive(left_diver_joystick->GetY(), right_diver_joystick->GetY());
	// control the intake arm motors
	Joystick *arm_control_joystick = Robot::oi->getArmControllerJoystick();
	Robot::intakeArm->controlIntakeArm(arm_control_joystick->GetY());
}
// Make this return true when this Command no longer needs to run execute()
bool TeleOpTankDrive::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void TeleOpTankDrive::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TeleOpTankDrive::Interrupted() {
	Robot::theDriveTrain->runTankDrive(0.0, 0.0);
}
