// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "TheDriveTrain.h"
#include "../Robotmap.h"
#include "../Commands/TeleOpTankDrive.h"
TheDriveTrain::TheDriveTrain() : Subsystem("TheDriveTrain") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	leftDriveMotorOne = RobotMap::theDriveTrainLeftDriveMotorOne;
	leftDriveMotorTwo = RobotMap::theDriveTrainLeftDriveMotorTwo;
	rightDriveMotorOne = RobotMap::theDriveTrainRightDriveMotorOne;
	rightDriveMotorTwo = RobotMap::theDriveTrainRightDriveMotorTwo;
	robotDriveController = RobotMap::theDriveTrainRobotDriveController;
	leftDriveEncoder = RobotMap::theDriveTrainLeftDriveEncoder;
	rightDriveEncoder = RobotMap::theDriveTrainRightDriveEncoder;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void TheDriveTrain::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new TeleOpTankDrive());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
//
// Run Tank Drive
// This method makes the robot drivalbe via tank drive during the teleop period.
// @example Robot::theDriveTrain->runTankDrive(1.0, 1.0);
// @param leftValue double
// @param rightValue double
void TheDriveTrain::runTankDrive(double leftValue, double rightValue) {
	robotDriveController->TankDrive(leftValue, rightValue);
}
//
// Stop Tank Drive
// This method makes the robot come to a full stop.
// @example Robot::theDriveTrain->stopTankDrive();
void TheDriveTrain::stopTankDrive() {
	robotDriveController->TankDrive(0.0, 0.0);
}
