// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "ThrowerArm.h"
#include "../Robotmap.h"
ThrowerArm::ThrowerArm() : Subsystem("ThrowerArm") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	throwerMotorOne = RobotMap::throwerArmThrowerMotorOne;
	throwerMotorTwo = RobotMap::throwerArmThrowerMotorTwo;
	throwerMotorThree = RobotMap::throwerArmThrowerMotorThree;
	throwerArmUpLimitSwitch = RobotMap::throwerArmThrowerArmUpLimitSwitch;
	throwerArmDownLimitSwitch = RobotMap::throwerArmThrowerArmDownLimitSwitch;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void ThrowerArm::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
//
// Launch Ball Based on Timing
// This method is used to launch the ball.
// @note This method only works fairly well if the robot is carring a ball.
// @example Robot::throwerArm->launchBallBasedOnTiming(0.5, 0.1);
// @param power double
// @param delay double
void ThrowerArm::launchBallBasedOnTiming(double power, double delay){
	throwerMotorOne->Set(power);
	throwerMotorTwo->Set(power);
	throwerMotorThree->Set(power);
	Wait(delay);
	throwerMotorOne->Set(0.0);
	throwerMotorTwo->Set(0.0);
	throwerMotorThree->Set(0.0);
}
//
// Move Motors Forward
// This method is used to retract the thrower after launch.
// @example Robot::throwerArm->moveMotorsForward(0.5);
// @param power double
void ThrowerArm::moveMotorsForward(double power){
	throwerMotorOne->Set(power);
	throwerMotorTwo->Set(power);
	throwerMotorThree->Set(power);
}
//
// Move Motors In Reverse
// This method is used to retract the thrower after launch in reverse.
// @note Explictly stating forwards or in reverse causes less confusion in conversations.
// @example Robot::throwerArm->moveMotorsInReverse(0.5);
// @param power double
void ThrowerArm::moveMotorsInReverse(double power){
	throwerMotorOne->Set(-power);
	throwerMotorTwo->Set(-power);
	throwerMotorThree->Set(-power);
}
//
// Is Fully Extended Up
// This method returns true if the thrower arm is fully extended.
// @example Robot::throwerArm->isFullyExtendedUp();
// @return boolean
bool ThrowerArm::isFullyExtendedUp(){
	return throwerArmUpLimitSwitch->Get();
}
//
// Is Fully Retracted Down
// This method returns true if the thrower arm is fully retracted.
// @example Robot::throwerArm->isFullyRetractedDown();
// @return boolean
bool ThrowerArm::isFullyRetractedDown(){
	return throwerArmDownLimitSwitch->Get();
}
